name: Upload Data

on:
  schedule:
    - cron: "0 0-23/4 * * *"
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    container:
      image: naoigcat/s3s:latest
    env:
      CONFIG: ${{ secrets.CONFIG }}
    steps:
      -
        name: Generate config.txt
        working-directory: /opt/s3s
        if: env.CONFIG != ''
        run: |
          echo $CONFIG > /opt/s3s/config.txt
      -
        name: Upload Data
        working-directory: /opt/s3s
        if: env.CONFIG != ''
        run: |
          wait_time=60
          until python3 s3s.py -r || test $wait_time -eq 180
          do
            sleep $(( wait_time += 60 ))
          done
